### ISSUE TITLE
Python OpenEye check is broken

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/drug-computing#15]
@nathanmlim - in the getting started info (https://github.com/MobleyLab/drug-computing/blob/master/uci-pharmsci/getting-started.md) you have something like:
```
Verify the installation with:

python oecheminfo.py
The output should look something like:
```

I get a "can't open file" message when I do that. :) Probably you're missing a step about paths?

**Comment by nathanmlim** [comment]
Somehow missed this notification. It looks like the installation verification test *use* to work with `python oecheminfo.py`. Now, it's just `oecheminfo.py` according to the [latest docs](https://docs.eyesopen.com/toolkits/python/quickstart-python/linuxosx.html#anaconda-installation)

**Comment by davidlmobley** [comment]
Resolved.
