### ISSUE TITLE
Write `pdb` files with original oemols in solvation notebook

### ISSUE THREAD

**Issue by bannanc** [MobleyLab/drug-computing#49]
We discovered a potential issue in the order files are created in [`drug-computing/uci-pharmsci/lectures/solvation/solvation.ipynb`](https://github.com/MobleyLab/drug-computing/blob/master/uci-pharmsci/lectures/solvation/solvation.ipynb). It was illustrated and discussed in [SMIRNOFF99Frosst issue#71](https://github.com/openforcefield/smirnoff99Frosst/issues/71). 

I think the easiest way to fix it (and what I did while testing) is to write out the pdb file at the beginning of the `gas_phase_MD` and `GBSA_MD` methods with the original oemol instead of trying to convert the openmm system back to a oemol at the end of the simulation.

**Comment by davidlmobley** [comment]
Resolved by other modernization
