### ISSUE TITLE
Remove html versions of notebooks

### ISSUE THREAD

**Issue by matthagy** [MobleyLab/drug-computing#80]
Github now supports [natively rendering Jupyter notebooks in the web UI](https://github.blog/2015-05-07-github-jupyter-notebooks-3/). Additionally, I tried downloading one of the html files and it includes broken images. See the following example.

<img width="878" alt="Screen Shot 2019-10-26 at 5 37 15 AM" src="https://user-images.githubusercontent.com/741911/67617613-bede7480-f7b2-11e9-885a-9ec201f49afe.png">

I can put together a PR to remove these files if the owners of this project think this is reasonable.

**Comment by davidlmobley** [comment]
I'd love your contribution! There's a lot here that could use improving, but I have pretty limited time to do it, so this would be lovely. Thanks for your interest!

**Comment by davidlmobley** [comment]
Were you still interested in doing this, @matthagy ? If not I should put it on my list, as I'm getting ready to do this course again. :)

**Comment by davidlmobley** [comment]
Resolved in #98
